##################################################
# oretademosite service
########################################### 
apiVersion: v1
kind: Service
metadata:
  name: oretademosite
  # namespace: oreta-namespace
  labels:
    app: oretademosite
spec:
  ports:
  - port: 9081
    name: http
  selector:
    app: oretademosite
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: oretademosite-v1
  # namespace: oreta-namespace
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: oretademosite
        version: v1
    spec:
      containers:
      - name: oretademosite
        image: asia.gcr.io/vantage2018-gke/website:v5.0
        # env:
        # - name: GOOGLE_APPLICATION_CREDENTIALS
        #   value: /Users/donsantmajor/.config/gcloud/oretagcp07-9f7f4197ecef.json        
        # resources:
        #   requests:
        #     cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 9081
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: oretademosite-v2
  # namespace: oreta-namespace
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: oretademosite
        version: v2
    spec:
      containers:
      - name: oretademosite
        image: asia.gcr.io/vantage2018-gke/website:v4.0
        # env:
        # - name: GOOGLE_APPLICATION_CREDENTIALS
        #   value: /Users/donsantmajor/.config/gcloud/oretagcp07-9f7f4197ecef.json
        # resources:
        #   requests:
        #     cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 9081
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: oretademosite-v3
  # namespace: oreta-namespace
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: oretademosite
        version: v3
    spec:
      containers:
      - name: oretademosite
        image: asia.gcr.io/vantage2018-gke/website:v3.0
        # env:
        # - name: GOOGLE_APPLICATION_CREDENTIALS
        #   value: /Users/donsantmajor/.config/gcloud/oretagcp07-9f7f4197ecef.json
        # resources:
        #   requests:
        #     cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 9081
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: oretademosite-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: oretademosite
spec:
  hosts:
  - "*"
  gateways:
  - oretademosite-gateway
  http:
  - match:
    - uri:
        exact: /demo
    route:
    - destination:
        host: oretademosite
        port:
          number: 9081

